name: dp-fibonacci-python
on: [ push, pull_request ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.9'
                    architecture: 'x64'
            -   name: Install dependencies
                run: |
                    make deps
                    make dev-deps
            -   name: Lint with flake8
                run: |
                    make checkstyle
            -   name: Test with pytest
                run: |
                    make test
            -   name: Upload pytest test results
                uses: actions/upload-artifact@v2
                with:
                    name: pytest-results
                    path: junit/test-results.xml
                # Use always() to always run this step to publish test results when there are test failures
                if: ${{ always() }}


